### ISSUE TITLE
Server crashes on GET /products/:id?system={system-name}

### ISSUE THREAD

**Issue by danielmwakanema** [Kuunika/Product-Master#27]
When a <b>system</b> is specified and the product is not found the server crashes.
I reckon the code below might be causing the issue:
```typescript
    try {
      const searchResults = await (
        await this.axiosClient.get<OclMappingsSearchResult[]>(url)
      ).data;
      if (searchResults.length === 1) {
        const product = searchResults[0];
        return this.getProductByCode(product.from_concept_code);
      }
    } catch (error) {
      this.axiosErrorHandling(error, url, system, productCode);
    }
```
If the product is not found it'll Promise undefined then the formatters will try to call id, name and so on, on undefined. I think.

**Comment by brett-onions** [comment]
Thanks for pointing this out. It has been fixed in the latest version.
